import React from "react";
import Header from "../../component//components/header/header";
import Section2 from "../../component//components/section2/section2";
import Section3 from "../../component//components/section3/section3";
import Section4 from "../../component//components/section4/section4";
import Section5 from "../../component//components/section5/section5";
import Section6 from "../../component//components/section6/section6";
import Footer from "../../component//components/footer/footer";
import Layout from '@/component/layout/Layout'
import Head from 'next/head'


const contact = () => {

  return (
    <>
    <Head>
        <title>official - disclaimer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon"/>
    </Head>
    <Layout>
    <Header />
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />
      <Section6 />
      {/* <PopUp
        color="linear-gradient(270deg, rgba(7, 2, 45, 1) 0%, rgba(42, 56, 96, 1) 52%, rgba(0, 212, 255, 1) 100%)"
        url="//logo.png"
        logoWidth="230px !important"
        number="+1(855)-316-1700"
      /> */}
      <Footer />
    </Layout>
    </>
  )
}

export default contact